# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10eb406223fc72200cf4ae7a04f59b11ff15eec0b0d84e440fd4f08fb2dc820dda85372569128717ce18bf9ad0313013c83bf7e01b596bf3fcd13d13c7923015

test:
  secret_key_base: 73b1517c38c0cc3a783af36440585d22fafff49e1dea487c5e4d5b1ad144d8481aa51680c6a93e09df65512b6b932c748d3cfe37c777240486cb456972202a8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
